'use strict';

/*
 * Assemble the full published site: a marketing landing page at the root, with
 * the installable PWA underneath it at /app/.
 *
 * Why this exists: scripts/build-pwa.js already produces a complete, installable
 * offline app in dist-pwa/, and .github/workflows/pages.yml publishes that
 * directory to GitHub Pages. But it publishes the *app* at the site root, so a
 * first-time visitor lands in an empty PDF viewer with no explanation of what
 * FieldMark is, who it's for, or that there are desktop/Android builds.
 *
 * This step wraps build-pwa.js rather than modifying it:
 *
 *   1. run build-pwa.js untouched      -> dist-pwa/          (the app)
 *   2. relocate that whole tree        -> dist-pwa/app/
 *   3. copy site/                      -> dist-pwa/          (the landing page)
 *   4. copy docs/screenshots/          -> dist-pwa/img/
 *   5. copy a sample drawing           -> dist-pwa/app/demo/
 *   6. .nojekyll, 404.html, /app.html redirect, optional CNAME
 *
 * Keeping the relocation *after* build-pwa.js means the PWA bundle is byte-for-
 * byte what it has always been — only its directory changes. That matters
 * because every path build-pwa.js emits is already relative (start_url './',
 * scope './', relative icons, and a service-worker precache list resolved
 * against self.registration.scope), so the app works identically at a domain
 * root, a project sub-path, or a sub-directory of either.
 *
 * Electron and Capacitor are untouched: both consume www/, which this script
 * never modifies.
 *
 * Run: node scripts/build-site.js   (or `npm run build:site`)
 * Verify: `npm run verify:site`
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const SITE = path.join(ROOT, 'site');
const OUT = path.join(ROOT, 'dist-pwa');
const APP = path.join(OUT, 'app');
const SHOTS = path.join(ROOT, 'docs', 'screenshots');

// Screenshots the landing page references. An explicit list (rather than "copy
// whatever is in the folder") so a renamed or missing file fails the build here
// instead of shipping a broken <img> to production.
const REQUIRED_SHOTS = ['hero.png', 'markup.png', 'measure.png', 'organize.png', 'signature.png', 'mobile.png'];

// The sample drawing behind the landing page's "try it in your browser" CTA.
// Reuses the E2E fixture so it is regenerated by `npm run fixtures` alongside
// everything else and can never drift into an unopenable state unnoticed.
const DEMO_SRC = path.join(ROOT, 'test', 'fixtures', 'sample.pdf');
const DEMO_NAME = 'sample.pdf';

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function die(msg) {
  console.error('[build-site] ' + msg);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 1. Build the PWA exactly as before. Run as a child process so its top-level
//    side effects stay isolated and any failure surfaces verbatim.
// ---------------------------------------------------------------------------
console.log('[build-site] building the app bundle (dist-pwa/) …');
execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'build-pwa.js')], { stdio: 'inherit' });

if (!fs.existsSync(path.join(OUT, 'index.html'))) {
  die('build-pwa.js did not produce dist-pwa/index.html — aborting.');
}

// ---------------------------------------------------------------------------
// 2. Relocate dist-pwa/ -> dist-pwa/app/. A directory cannot be renamed into
//    itself, so pivot through a sibling: dist-pwa -> .dist-pwa-app, then
//    recreate dist-pwa and move the old tree in as app/.
// ---------------------------------------------------------------------------
const PIVOT = path.join(ROOT, '.dist-pwa-app');
rmrf(PIVOT);
fs.renameSync(OUT, PIVOT);
fs.mkdirSync(OUT, { recursive: true });
fs.renameSync(PIVOT, APP);
console.log('[build-site] app relocated -> dist-pwa/app/');

// ---------------------------------------------------------------------------
// 3. Landing page: copy site/ to the published root.
// ---------------------------------------------------------------------------
if (!fs.existsSync(path.join(SITE, 'index.html'))) die('site/index.html is missing.');
for (const entry of fs.readdirSync(SITE, { withFileTypes: true })) {
  // CNAME is handled in step 6 so its presence/absence is logged explicitly.
  if (entry.name === 'CNAME') continue;
  const s = path.join(SITE, entry.name);
  const d = path.join(OUT, entry.name);
  if (entry.isDirectory()) copyDir(s, d);
  else fs.copyFileSync(s, d);
}
console.log('[build-site] landing page copied -> dist-pwa/');

// ---------------------------------------------------------------------------
// 4. Screenshots the landing page shows off. Same PNGs the README uses, so
//    `npm run screenshots` refreshes both at once.
// ---------------------------------------------------------------------------
const imgOut = path.join(OUT, 'img');
fs.mkdirSync(imgOut, { recursive: true });
for (const name of REQUIRED_SHOTS) {
  const src = path.join(SHOTS, name);
  if (!fs.existsSync(src)) {
    die('missing screenshot docs/screenshots/' + name + '\n  run `npm run screenshots` first.');
  }
  fs.copyFileSync(src, path.join(imgOut, name));
}
console.log('[build-site] ' + REQUIRED_SHOTS.length + ' screenshots copied -> dist-pwa/img/');

// ---------------------------------------------------------------------------
// 5. Sample drawing for the in-app demo button.
//
//    Deliberately copied AFTER build-pwa.js generated the service worker, so it
//    is not in the precache list: a first-time visitor should not pay to
//    download it before deciding to click. The service worker's fetch handler
//    caches same-origin responses as they are requested, so the first
//    successful demo load makes it available offline from then on.
// ---------------------------------------------------------------------------
if (!fs.existsSync(DEMO_SRC)) {
  die('missing demo drawing test/fixtures/sample.pdf\n  run `npm run fixtures` first.');
}
const demoOut = path.join(APP, 'demo');
fs.mkdirSync(demoOut, { recursive: true });
fs.copyFileSync(DEMO_SRC, path.join(demoOut, DEMO_NAME));

// Tell the renderer a demo exists, by declaring it in the app's own HTML.
//
// The alternative — having the renderer probe for the file at boot — makes every
// build that DOESN'T ship one (Electron over file://, the Capacitor bundle, and
// the plain www/ bundle that verify-web.js drives) emit a failed request. This
// way the deployment that actually ships a sample is the thing that says so, no
// probe and no platform branch in the app code.
const appHtmlPath = path.join(APP, 'index.html');
let appHtml = fs.readFileSync(appHtmlPath, 'utf8');
const demoMeta = '\n  <meta name="fieldmark-demo" content="demo/' + DEMO_NAME + '" />\n';
if (!appHtml.includes('name="fieldmark-demo"')) {
  appHtml = appHtml.replace(/<\/head>/, demoMeta + '</head>');
  fs.writeFileSync(appHtmlPath, appHtml, 'utf8');
}
console.log('[build-site] demo drawing copied -> dist-pwa/app/demo/' + DEMO_NAME);

// ---------------------------------------------------------------------------
// 6. Host files.
// ---------------------------------------------------------------------------

// GitHub Pages: serve the tree verbatim, no Jekyll. build-pwa.js already wrote
// one inside the app; the published root needs its own.
fs.writeFileSync(path.join(OUT, '.nojekyll'), '', 'utf8');

// Unknown paths get the landing page rather than GitHub's default 404. Pages
// serves 404.html for any unmatched request.
fs.copyFileSync(path.join(OUT, 'index.html'), path.join(OUT, '404.html'));

// Bookmark rescue: the app used to live at the site root, so anyone who saved
// that URL now lands on the marketing page. /app.html is a cheap, CSP-safe
// meta-refresh stub pointing at the app's new home.
fs.writeFileSync(path.join(OUT, 'app.html'),
  '<!doctype html>\n' +
  '<html lang="en">\n' +
  '<head>\n' +
  '  <meta charset="utf-8" />\n' +
  '  <title>FieldMark — opening the app…</title>\n' +
  '  <meta http-equiv="refresh" content="0; url=app/" />\n' +
  '  <link rel="canonical" href="app/" />\n' +
  '</head>\n' +
  '<body>\n' +
  '  <p>Opening FieldMark… <a href="app/">Continue to the app</a>.</p>\n' +
  '</body>\n' +
  '</html>\n', 'utf8');

// Custom domain. Optional by design: the domain is not bought yet, and adding
// site/CNAME later should be a one-file change with no code edit.
const cname = path.join(SITE, 'CNAME');
if (fs.existsSync(cname)) {
  fs.copyFileSync(cname, path.join(OUT, 'CNAME'));
  console.log('[build-site] CNAME -> ' + fs.readFileSync(cname, 'utf8').trim());
} else {
  console.log('[build-site] no site/CNAME — publishing on the default github.io domain');
}

console.log('[build-site] done. Landing page at dist-pwa/, app at dist-pwa/app/.');
